### PR TITLE
unhide/display current search results on click (to fix #355)

### LINKED ISSUE #355: Clicking on Geocoder input field should expand suggestions/results list (even after selecting a result)
Currently, it is cumbersome to navigate through multiple geocode results as it is difficult to unhide the suggestions list after selecting a result.

Reproduction steps below:

1. Use the live example at https://maplibre.org/maplibre-gl-js/docs/examples/geocoder/
2. Search for "city", this should offer multiple results
3. Click on any search result (this will hide the suggestions list)
4. Attempt to unhide the suggestions list (in order to navigate to a different search result) by clicking on input field. This is only possible by using select all (Ctrl+A) on the Geocoder input field

This might be a bug as the desired behavior is lost after selecting a result and regained after doing the "Ctrl + A" trick.

### PR DESCRIPTION
**Pull request by prusswan**
- [x] briefly describe the changes in this PR

After an item has been selected from the suggestions list, the list will be cleared (so unhiding the list is not enough as the UI contents are gone - however, data is still present in `geocoder._typeahead.data`). Hence, I added an event handler on "click" to trigger `geocoder._typeahead.update` to repopulate the suggestions list from `geocoder._typeahead.data`.

### CODE REVIEW

File: lib/index.ts [hunk 1]
```diff
@@ -528,6 +528,11 @@ export default class MaplibreGeocoder {
       noInitialSelection: true,
     });
 
+    var that = this;
```
Comment (HarelM) [inline lib/index.ts]: This is not needed in typescript, use lambda instead.

File: lib/index.ts [hunk 2]
```diff
@@ -528,6 +528,11 @@ export default class MaplibreGeocoder {
...
+    this.container.addEventListener("mouseenter", function() {
```
Comment (HarelM) [inline lib/index.ts]: Why mouseenter and not focus event? What will happen on mobile devices?

Comment (HarelM) [reply lib/index.ts]: Wouldn't this create memory leak if control is removed?

Comment (prusswan) [reply lib/index.ts]: > Why mouseenter and not focus event? What will happen on mobile devices?

"click" is safer then. "focus" does not work if the user just switches between different search results without clicking outside of the input (so focus is never lost)

> Wouldn't this create memory leak if control is removed?

No different from the event listeners earlier, like:

https://github.com/maplibre/maplibre-gl-geocoder/blob/2ba126abf6738e66b73916d7051a58e8016c6b7d/lib/index.ts#L492-L493

File: lib/index.ts (hunk 1 above)
Comment (prusswan) [reply lib/index.ts]: done

**Comment by HarelM** [comment]
Can you add a test for this scenario or is this already covered in the tests?

**Comment by prusswan** [comment]
> Can you add a test for this scenario or is this already covered in the tests?

Added the test

**Comment by HarelM** [comment]
Thanks! Sorry for nagging, but is there any chance you could use the existing unit tests to add a test? I think the browser test should be a last resort as this is not covered by the coverage report...

**Comment by HarelM** [comment]
It seems that the code is covered by tests somehow, so it might be an easy asserting addition to an existing test maybe?

**Comment by prusswan** [comment]
> Thanks! Sorry for nagging, but is there any chance you could use the existing unit tests to add a test? I think the browser test should be a last resort as this is not covered by the coverage report...

Not sure how it should work as a unit test as the browser test aptly describes the scenario. I think the root cause is due to suggestions-list but if we accept its behavior and choose to fix the issue in this library, then integration test makes more sense

**Comment by HarelM** [comment]
Fair enough.

**Review by HarelM — APPROVED** [review]
