### PR TITLE
Fix _onKeyDown not working when map is inside custom web component

### LINKED ISSUE #19: _onKeyDown not working when map is inside custom web component
When using maplibre In a custom web component, the selection for the value doesn't work properly. The Active element in  the shadow root isn't the input element itself. My recommendation would be to use the value of  ```this._inputEl``` because there's already a reference to it.
Screen Shot 2021-12-20 at 12 01 09

### PR DESCRIPTION
**Pull request by TownCube**
## Background

- Fixes #19
- Replicated in [JSFiddle](https://jsfiddle.net/TownCube/27wojtrz/) when typing into the search box

### Options
1. Use the existing `_inputEl` variable per the recommendation in #19 
2. Add recursive handling to walk down all the shadow roots rather then just the first one. For example, the current two nested shadow DOM issue I'm encountered is fixed by extending the existing lookup to `e.target.shadowRoot.activeElement.shadowRoot.activeElement`

### Implementation
I've gone with option 1 because there is already existing code for handling the escape key that relies on the `_inputEl` variable that appears earlier then where `value` is set. I've also removed the handling for if the `target` is missing on the basis the earlier code assumes `_inputEl` exists without a check.

I've tried to add a unit test however jsdom doesn't set the target to the shadow DOM in the same way as the browser does so I've manually set it. I've created [a JSFiddle](https://jsfiddle.net/TownCube/27wojtrz/) to replicate the issue to verify that the target is the host shadow DOM element.

image

## Other changes
- Added a local development flow to [CONTRIBUTING.md](https://github.com/maplibre/maplibre-gl-geocoder/pull/234/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055)
- Call `build` script from `watch` script rather then having a copy/pasted command which could fall out of sync over time.
- Upgraded `maplibre-gl` to `5.0.1` in [test/test.html](https://github.com/maplibre/maplibre-gl-geocoder/pull/234/files#diff-94800a2c52169659e5a53b6f4ce10ef4fb1a53fb1d6bec7a0277b2ea75680190)

## Checklist

 - [x] briefly describe the changes in this PR
 - [x] write tests for all new functionality
 - [x] update CHANGELOG.md with changes under `main` heading before merging

## JSFiddle Backup
<details>
<summary>HTML</summary>

````html
<script src="https://unpkg.com/maplibre-gl@^5.0.1/dist/maplibre-gl.js"></script>
<script src="https://unpkg.com/@maplibre/maplibre-gl-geocoder@1.7.1/dist/maplibre-gl-geocoder.js"></script>

<template id="custom-map">
  <link
    rel="stylesheet"
    href="https://unpkg.com/maplibre-gl@^5.0.1/dist/maplibre-gl.css"
  />
  <link
    rel="stylesheet"
    href="https://unpkg.com/@maplibre/maplibre-gl-geocoder@1.7.1/dist/maplibre-gl-geocoder.css"
  />
  <style>
    #map {
      width: 100%;
      height: 400px;
    }
  </style>
  <div id="map"></div>
</template>

<div id="host">
</div>
````
</details>

<details>
<summary>JavaScript</summary>

````js
const host = document.querySelector("#host")
const shadowWrapper = host.attachShadow({
  mode: "open",
  delegatesFocus: "true",
})
const wrapper = document.createElement("div")
shadowWrapper.appendChild(wrapper)

const shadow = wrapper.attachShadow({ mode: "open", delegatesFocus: "true" })

const template = document.getElementById("custom-map")
shadow.appendChild(template.content)

const geocoderApi = {
  forwardGeocode: async (config) => {
    const features = []
    try {
      const request = `https://nominatim.openstreetmap.org/search?q=${
        config.query
      }&format=geojson&polygon_geojson=1&addressdetails=1`
      const response = await fetch(request)
      const geojson = await response.json()
      for (const feature of geojson.features) {
        const center = [
          feature.bbox[0] + (feature.bbox[2] - feature.bbox[0]) / 2,
          feature.bbox[1] + (feature.bbox[3] - feature.bbox[1]) / 2,
        ]
        const point = {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: center,
          },
          place_name: feature.properties.display_name,
          properties: feature.properties,
          text: feature.properties.display_name,
          place_type: ["place"],
          center,
        }
        features.push(point)
      }
    } catch (e) {
      console.error(`Failed to forwardGeocode with error: ${e}`)
    }

    return {
      features,
    }
  },
}

const map = new maplibregl.Map({
  container: shadow.querySelector("#map"), // container id
  style: "https://demotiles.maplibre.org/style.json", // style URL
  center: [0, 0], // starting position [lng, lat]
  zoom: 1, // starting zoom
})

map.addControl(
  new MaplibreGeocoder(geocoderApi, {
    maplibregl,
  }),
)
````
</details>

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks! Looks like a simple fix. 
Is there a chance to add a test to cover this scenario?

**Comment by TownCube** [comment]
> Thanks! Looks like a simple fix.
> Is there a chance to add a test to cover this scenario?

Thanks @HarelM, I've added a test but I don't think the Shadow DOM handling in jsdom is robust enough as the `target` is not set in the same way as I see in the browser. I've tried to manually set the target read only property to match what I see in the browser. Setting a read only property is bad, so any suggestions on a better way to handle this are welcome.

**Comment by HarelM** [comment]
What about adding a test that runs in the browser? Cypress maybe, or something simpler - puppeteer/playwrite?

**Comment by TownCube** [comment]
> What about adding a test that runs in the browser? Cypress maybe, or something simpler - puppeteer/playwrite?

I've added a browser test aligning with maplibre-gl-js using puppeteer and vitest.

File: lib/index.ts [hunk 1]
```diff
@@ -610,12 +610,7 @@ export default class MaplibreGeocoder {
       return this._inputEl.blur();
     }
 
-    // if target has shadowRoot, then get the actual active element inside the shadowRoot
-    const target =
-      e.target && e.target.shadowRoot
-        ? e.target.shadowRoot.activeElement
-        : e.target;
-    const value = target ? target.value : "";
+    const value = this._inputEl.value;
```
Comment (HarelM) [inline lib/index.ts:613]: I think the code above was an attempt to solve something similar, can you check that this change didn't broke it?

File: package.json [hunk 2]
```diff
@@ -7,11 +7,13 @@
...
   "style": "dist/maplibre-gl-geocoder.css",
   "scripts": {
-    "watch": "rollup --configPlugin @rollup/plugin-typescript -c --watch",
+    "watch": "npm run build -- --watch",
     "build": "rollup --configPlugin @rollup/plugin-typescript -c",
     "build-css": "mkdir -p dist && cp lib/index.css dist/maplibre-gl-geocoder.css",
     "build-dist": "npm run build && npm run build-css",
-    "test": "jest",
+    "test": "npm run test-unit && npm run test-integration",
+    "test-unit": "jest",
```
Comment (HarelM) [inline package.json:15]: If you feel like replacing jest with vite that would also be great, not part of this PR I guess...

**Comment by HarelM** [comment]
Thanks! Did you make sure the test fails without the fix?
Otherwise, this looks good.

File: lib/index.ts (hunk 1 above)
Comment (TownCube) [reply lib/index.ts:613]: I'm not sure I fully understand the question so please feel free to clarify further. The code above's behaviour which clears when the escape button is pressed is verified by the existing `options.clearAndBlurOnEsc=true clears and blurs on escape` unit test. I've also tested it works manually.

File: package.json (hunk 2 above)
Comment (TownCube) [reply package.json:15]: I've migrated the unit tests [in a separate branch](https://github.com/TownCube/maplibre-gl-geocoder/commit/e769be37c309eb9bea1f16dee4c0f0a29f18e653), happy to put that in either this PR or raise a new PR once this one is approved.

**Comment by TownCube** [comment]
> Thanks! Did you make sure the test fails without the fix?

I've [screencast a video of the test running](https://github.com/TownCube/maplibre-gl-geocoder/actions/runs/12952655085/artifacts/2481564379) after [reverting the fix](https://github.com/TownCube/maplibre-gl-geocoder/actions/runs/12952655085), you can see the test fighting the clear firing on each keypress.

File: package.json (hunk 2 above)
Comment (HarelM) [reply package.json:15]: Cool thanks! A different PR would be better I think.

File: lib/index.ts (hunk 1 above)
Comment (HarelM) [reply lib/index.ts:613]: In the code you replaced the was a mention of shadowRoot, which seems similar to what you want to solve. Can you check in the history of this repo to see if you can find the root cause reason the original code was introduced?

**Review by HarelM — APPROVED** [review]

File: lib/index.ts (hunk 1 above)
Comment (TownCube) [reply lib/index.ts:613]: The original code fixes the issue with the plugin being used in a single level shadow root. However the code fails to account for the possibility of its use within multiple nested shadow roots.

If we wanted the retain the existing approach of using `target` we could loop down the shadow roots [similar to how the map itself handles them](https://github.com/maplibre/maplibre-gl-js/blob/ef74795676d4e6a7c3b89b52a1ff068fa2ad5955/src/ui/control/fullscreen_control.ts#L121-L123).

However I'd worry looping down the roots wouldn't be as efficient as using the existing reference we already have in `_inputEl`.

The function `_onKeyDown` is only ever attached as a listener of key down against `_inputEl` so I can't see how target would ever be anything else.

Comment (HarelM) [reply lib/index.ts:613]: Ok, thanks for the info!
